spring:
  datasource:
    url: jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

flowable:
  rest:
    app:
      enabled: true
  check-process-definitions: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081

logging:
  level:
    root: INFO
    org.flowable: DEBUG