spring:
  datasource:
    generate-unique-name: false
    url: jdbc:mysql://localhost:3306/flowable_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: default
    generate-ddl: false
    properties:
      connection:
        charSet: utf-8
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: true
    url: jdbc:mysql://localhost:3306/flowable_db
    user: admin
    password: admin
    out-of-order: true

flowable:
  rest:
    app:
      enabled: true
  check-process-definitions: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081

logging:
  level:
    root: INFO
    org.flowable: DEBUG