spring:
  datasource:
    generate-unique-name: false
    url: jdbc:mysql://localhost:3306/flowable_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      media-types:
        wav: audio/wav
      static-locations: file:/home/alexander/IdeaProjects/java-flowable-workflow/src/main/resources/mystatic/
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: default
    generate-ddl: false
    properties:
      connection:
        charSet: utf-8
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: true
    url: jdbc:mysql://localhost:3306/flowable_db
    user: admin
    password: admin
    out-of-order: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/  #this is the main
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  messages:
    basename: messages
    encoding: UTF-8

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

flowable:
  rest:
    app:
      enabled: true
  check-process-definitions: true
  cmmn:
    enabled: true
  dmn:
    enabled: true
  form:
    enabled: true
  content:
    enabled: true
  idm:
    enabled: true # Identity обычно нужен для пользователей

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081

springdoc:
  info:
    title: Neural Network API
    version: 1.0
    description: API for Neural Network Management
  api-docs:
    enabled: true        # Включить /v3/api-docs
    path: /v3/api-docs   # Путь (по умолчанию /v3/api-docs)
  swagger-ui:
    enabled: true        # Включить Swagger UI
    path: /swagger-ui.html  # Путь, куда перенаправлять (но по факту UI — это /swagger-ui/index.html)
    try-it-out-enabled: true  # Кнопка "Try it out"

logging:
  level:
    org.flowable: INFO
    org.springframework.boot.devtools: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN
    org.springframework.kafka: INFO
    org.apache.tomcat: INFO
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
    com.techmatrix18: DEBUG
    liquibase: WARN
    root: INFO
#    #org.thymeleaf: DEBUG